// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "users-api",
    "version": "1"
  },
  "paths": {
    "/users": {
      "post": {
        "summary": "createUser",
        "description": "",
        "operationId": "createUser.post./users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "getAllUsers",
        "description": "",
        "operationId": "getAllUsers.get./users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/people": {
      "get": {
        "summary": "getSWAPIPeople",
        "description": "",
        "operationId": "getSWAPIPeople.get.swapi/people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/people/{id}": {
      "get": {
        "summary": "getSWAPIPersonById",
        "description": "",
        "operationId": "getSWAPIPersonById.get.swapi/people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "detailed",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/films": {
      "get": {
        "summary": "getSWAPIFilms",
        "description": "",
        "operationId": "getSWAPIFilms.get.swapi/films",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/cache/stats": {
      "get": {
        "summary": "getSWAPICacheStats",
        "description": "",
        "operationId": "getSWAPICacheStats.get.swapi/cache/stats",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/docs": {
      "get": {
        "summary": "swaggerUI",
        "description": "",
        "operationId": "swaggerUI.get.docs",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swagger.json": {
      "get": {
        "summary": "swaggerJson",
        "description": "",
        "operationId": "swaggerJson.get.swagger.json",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};